import type {
  Appointment,
  Asset,
  AuditEntry,
  CallRecord,
  Consent,
  Conversation,
  Invoice,
  Lead,
  Location,
  Message,
  OnboardingStep,
  Outcome,
  Review,
  Rule,
  Tenant,
  UsageMeter,
  User,
  ActionItem,
} from "./types";

export const CLINIC = "ten_kapoor";
export const TRAVEL = "ten_sharma";
export const CA = "ten_mehta";

export function isoHoursAgo(h: number) {
  return new Date(Date.now() - h * 3600000).toISOString();
}

export const tenants: Tenant[] = [
  {
    id: CLINIC,
    name: "Kapoor Dental Studio",
    niche: "clinics",
    plan: "Core OS",
    status: "live",
    createdAt: isoHoursAgo(24 * 86),
    avgCaseValueInr: 12000,
    aiPaused: false,
    mrrInr: 42000,
    daysLive: 86,
    timezone: "Asia/Kolkata",
  },
  {
    id: TRAVEL,
    name: "Sharma Travels",
    niche: "travel",
    plan: "Core OS",
    status: "activation",
    createdAt: isoHoursAgo(24 * 4),
    avgCaseValueInr: null,
    aiPaused: false,
    mrrInr: 0,
    daysLive: 0,
    timezone: "Asia/Kolkata",
  },
  {
    id: CA,
    name: "Mehta & Co. CA",
    niche: "ca",
    plan: "Core OS",
    status: "churn_risk",
    createdAt: isoHoursAgo(24 * 140),
    avgCaseValueInr: 8000,
    aiPaused: true,
    mrrInr: 28000,
    daysLive: 140,
    timezone: "Asia/Kolkata",
  },
];

export const locations: Location[] = [
  {
    id: "loc_dwarka",
    tenantId: CLINIC,
    name: "Dwarka clinic",
    address: "Sector 22, Dwarka, New Delhi",
    timezone: "Asia/Kolkata",
    phone: "+91 11 4000 1200",
  },
  {
    id: "loc_jaipur",
    tenantId: TRAVEL,
    name: "Jaipur desk",
    address: "MI Road, Jaipur",
    timezone: "Asia/Kolkata",
    phone: "+91 141 400 2200",
  },
  {
    id: "loc_cp",
    tenantId: CA,
    name: "Connaught Place",
    address: "New Delhi",
    timezone: "Asia/Kolkata",
    phone: "+91 11 2335 0101",
  },
];

export const users: User[] = [
  {
    id: "usr_meera",
    tenantId: CLINIC,
    email: "meera@kapoordental.in",
    name: "Dr. Meera Kapoor",
    role: "owner",
    locationScope: "all",
    password: "demo123",
    totpEnabled: false,
  },
  {
    id: "usr_reception",
    tenantId: CLINIC,
    email: "staff@kapoordental.in",
    name: "Priya Reception",
    role: "staff",
    locationScope: "loc_dwarka",
    password: "demo123",
    totpEnabled: false,
  },
  {
    id: "usr_rahul",
    tenantId: TRAVEL,
    email: "rahul@sharmatravels.in",
    name: "Rahul Sharma",
    role: "owner",
    locationScope: "all",
    password: "demo123",
    totpEnabled: false,
  },
  {
    id: "usr_saurabh",
    tenantId: null,
    email: "saurabh@webwisedigital.net",
    name: "Saurabh Chugh",
    role: "webwise_admin",
    locationScope: "all",
    password: "demo123",
    totpEnabled: true,
  },
];

export const leads: Lead[] = [
  {
    id: "ld_ananya",
    tenantId: CLINIC,
    locationId: "loc_dwarka",
    name: "Ananya S.",
    phone: "+91 98xxx 11203",
    source: "Google Maps",
    channel: "whatsapp",
    intent: "Implant consultation Saturday",
    score: 86,
    scoreReasons: ["Named procedure", "Named time", "After-hours"],
    stage: "booked",
    ownerUserId: "usr_reception",
    createdAt: isoHoursAgo(9.2),
    tags: ["implant", "overnight"],
  },
  {
    id: "ld_rohit",
    tenantId: CLINIC,
    locationId: "loc_dwarka",
    name: "Rohit M.",
    phone: "+91 99xxx 88410",
    source: "Instagram",
    channel: "instagram",
    intent: "Whitening price",
    score: 54,
    scoreReasons: ["Price-first", "No date yet"],
    stage: "qualified",
    ownerUserId: null,
    createdAt: isoHoursAgo(8.7),
    tags: ["whitening", "escalated"],
  },
  {
    id: "ld_neha",
    tenantId: CLINIC,
    locationId: "loc_dwarka",
    name: "Neha K.",
    phone: "+91 88xxx 44102",
    source: "Landing page",
    channel: "site",
    intent: "Confirmed Saturday 11:00",
    score: 91,
    scoreReasons: ["Slot confirmed"],
    stage: "booked",
    ownerUserId: "usr_reception",
    createdAt: isoHoursAgo(10),
    tags: ["confirmed"],
  },
  {
    id: "ld_vikram",
    tenantId: CLINIC,
    locationId: "loc_dwarka",
    name: "Vikram D.",
    phone: "+91 97xxx 22011",
    source: "Site chat",
    channel: "site",
    intent: "Second opinion RCT",
    score: 70,
    scoreReasons: ["Clinical intent"],
    stage: "new",
    ownerUserId: null,
    createdAt: isoHoursAgo(12),
    tags: ["rct"],
  },
  {
    id: "ld_yesterday",
    tenantId: CLINIC,
    locationId: "loc_dwarka",
    name: "Sana Iqbal",
    phone: "+91 90xxx 33021",
    source: "WhatsApp",
    channel: "whatsapp",
    intent: "Scaling yesterday 4pm",
    score: 80,
    scoreReasons: ["Completed visit pending outcome"],
    stage: "showed",
    ownerUserId: "usr_meera",
    createdAt: isoHoursAgo(30),
    tags: ["needs_outcome"],
  },
  {
    id: "ld_noshow",
    tenantId: CLINIC,
    locationId: "loc_dwarka",
    name: "Arjun P.",
    phone: "+91 96xxx 11990",
    source: "Voice",
    channel: "voice",
    intent: "Missed consult Tue",
    score: 48,
    scoreReasons: ["No-show"],
    stage: "no_show",
    ownerUserId: "usr_reception",
    createdAt: isoHoursAgo(50),
    tags: ["no_show"],
  },
];

export const conversations: Conversation[] = [
  {
    id: "cv_ananya",
    leadId: "ld_ananya",
    tenantId: CLINIC,
    channel: "whatsapp",
    aiHandled: true,
    escalated: false,
    humanTakeover: false,
    sentiment: "positive",
  },
  {
    id: "cv_rohit",
    leadId: "ld_rohit",
    tenantId: CLINIC,
    channel: "instagram",
    aiHandled: true,
    escalated: true,
    humanTakeover: false,
    sentiment: "neutral",
  },
  {
    id: "cv_sana",
    leadId: "ld_yesterday",
    tenantId: CLINIC,
    channel: "whatsapp",
    aiHandled: true,
    escalated: false,
    humanTakeover: false,
    sentiment: "positive",
  },
];

export const messages: Message[] = [
  {
    id: "m1",
    conversationId: "cv_ananya",
    tenantId: CLINIC,
    direction: "in",
    body: "Hi, is implant consultation available this Saturday?",
    sentBy: "human",
    latencyMs: null,
    templateId: null,
    flaggedWrong: false,
    createdAt: isoHoursAgo(9.22),
  },
  {
    id: "m2",
    conversationId: "cv_ananya",
    tenantId: CLINIC,
    direction: "out",
    body: "Saturday 11:00 AM is available. Is this for a new implant or second opinion?",
    sentBy: "ai",
    latencyMs: 4200,
    templateId: "rule_implant",
    flaggedWrong: false,
    createdAt: isoHoursAgo(9.21),
  },
  {
    id: "m3",
    conversationId: "cv_rohit",
    tenantId: CLINIC,
    direction: "in",
    body: "Price for teeth whitening?",
    sentBy: "human",
    latencyMs: null,
    templateId: null,
    flaggedWrong: false,
    createdAt: isoHoursAgo(8.7),
  },
  {
    id: "m4",
    conversationId: "cv_rohit",
    tenantId: CLINIC,
    direction: "out",
    body: "Whitening starts at ₹8,000. I can book a 20-minute consult.",
    sentBy: "ai",
    latencyMs: 3800,
    templateId: "rule_whitening",
    flaggedWrong: false,
    createdAt: isoHoursAgo(8.69),
  },
];

export const appointments: Appointment[] = [
  {
    id: "ap_ananya",
    leadId: "ld_ananya",
    tenantId: CLINIC,
    slot: isoHoursAgo(-36),
    status: "booked",
    valueInr: null,
    recordedBy: "ai",
  },
  {
    id: "ap_neha",
    leadId: "ld_neha",
    tenantId: CLINIC,
    slot: isoHoursAgo(-36),
    status: "booked",
    valueInr: null,
    recordedBy: "ai",
  },
  {
    id: "ap_sana",
    leadId: "ld_yesterday",
    tenantId: CLINIC,
    slot: isoHoursAgo(20),
    status: "showed",
    valueInr: 4500,
    recordedBy: "usr_meera",
  },
  {
    id: "ap_arjun",
    leadId: "ld_noshow",
    tenantId: CLINIC,
    slot: isoHoursAgo(48),
    status: "no_show",
    valueInr: null,
    recordedBy: "usr_reception",
  },
];

export const outcomes: Outcome[] = [];

export const rules: Rule[] = [
  {
    id: "rule_implant",
    tenantId: CLINIC,
    trigger: "new_enquiry",
    condition: "mentions implant",
    response: "Saturday 11:00 AM is available. Is this for a new implant or second opinion?",
    approvedBy: "usr_meera",
    version: 3,
    active: true,
  },
  {
    id: "rule_whitening",
    tenantId: CLINIC,
    trigger: "price_question",
    condition: "mentions whitening",
    response: "Whitening starts at ₹8,000. I can book a 20-minute consult.",
    approvedBy: "usr_meera",
    version: 1,
    active: true,
  },
];

export const reviews: Review[] = [
  {
    id: "rv1",
    tenantId: CLINIC,
    locationId: "loc_dwarka",
    platform: "Google",
    rating: 2,
    text: "Waited 40 minutes.",
    requestedAt: isoHoursAgo(6),
    respondedAt: null,
    aiDraft: "Thank you for telling us. We are sorry about the wait — reception will message you privately to make this right.",
  },
  {
    id: "rv2",
    tenantId: CLINIC,
    locationId: "loc_dwarka",
    platform: "Google",
    rating: 5,
    text: "Night WhatsApp reply booked my implant consult.",
    requestedAt: isoHoursAgo(40),
    respondedAt: isoHoursAgo(38),
    aiDraft: null,
  },
];

export const assets: Asset[] = [
  {
    id: "pg_implant",
    tenantId: CLINIC,
    type: "page",
    name: "Implant consult",
    status: "live",
    url: "https://kapoor.webwise.site/implant",
    views: 1104,
    conversionRate: 11.2,
    leads: 124,
    publishedAt: isoHoursAgo(24 * 40),
  },
  {
    id: "pg_white",
    tenantId: CLINIC,
    type: "page",
    name: "Whitening offer",
    status: "live",
    url: "https://kapoor.webwise.site/whitening",
    views: 812,
    conversionRate: 8.1,
    leads: 66,
    publishedAt: isoHoursAgo(24 * 20),
  },
];

export const usage: UsageMeter[] = [
  { tenantId: CLINIC, meter: "wa_conversations", period: "2026-08", consumed: 820, included: 1000 },
  { tenantId: CLINIC, meter: "ai_calls", period: "2026-08", consumed: 4100, included: 8000 },
  { tenantId: CLINIC, meter: "voice_minutes", period: "2026-08", consumed: 0, included: 0 },
];

export const invoices: Invoice[] = [
  {
    id: "inv_aug",
    tenantId: CLINIC,
    razorpayId: "pay_demo_aug",
    amountInr: 42000,
    status: "paid",
    pdfUrl: "#",
    period: "Aug 2026",
  },
];

export const consents: Consent[] = leads.map((l) => ({
  id: `cs_${l.id}`,
  leadId: l.id,
  tenantId: l.tenantId,
  basis: "enquiry_consent",
  capturedAt: l.createdAt,
  source: l.channel,
  revokedAt: null,
}));

export const onboarding: OnboardingStep[] = [
  { id: "ob1", tenantId: TRAVEL, title: "Connect WhatsApp", owner: "webwise", dueAt: isoHoursAgo(-24), done: true },
  { id: "ob2", tenantId: TRAVEL, title: "Verify number", owner: "client", dueAt: isoHoursAgo(-12), done: true },
  { id: "ob3", tenantId: TRAVEL, title: "Set business hours", owner: "client", dueAt: isoHoursAgo(-6), done: false },
  { id: "ob4", tenantId: TRAVEL, title: "Approve first rules", owner: "client", dueAt: isoHoursAgo(-48), done: false },
  { id: "ob5", tenantId: TRAVEL, title: "Publish first page", owner: "webwise", dueAt: isoHoursAgo(-72), done: false },
  { id: "ob6", tenantId: TRAVEL, title: "Set average case value", owner: "client", dueAt: isoHoursAgo(-72), done: false },
];

export const calls: CallRecord[] = [
  {
    id: "c1",
    tenantId: CLINIC,
    leadId: "ld_noshow",
    who: "+91 96xxx 11990",
    at: isoHoursAgo(50),
    outcome: "Missed — not recovered",
    missed: true,
    recovered: false,
    transcript: "Missed after 2 rings.",
    minutes: 0,
  },
];

export const actionItems: ActionItem[] = [
  {
    id: "aq1",
    tenantId: CLINIC,
    kind: "escalated_chat",
    title: "Rohit M. asked price — AI waiting for human",
    href: "/leads/ld_rohit",
    createdAt: isoHoursAgo(8.6),
  },
  {
    id: "aq2",
    tenantId: CLINIC,
    kind: "unconfirmed_appt",
    title: "Ananya Saturday 11:00 not confirmed by reception",
    href: "/leads/ld_ananya",
    createdAt: isoHoursAgo(9),
  },
  {
    id: "aq3",
    tenantId: CLINIC,
    kind: "negative_review",
    title: "2-star Google review unresponded (6h)",
    href: "/reviews",
    createdAt: isoHoursAgo(6),
  },
];

export const audit: AuditEntry[] = [];
